---
plugins:
  - react
extends:
- airbnb
- plugin:react/recommended
env:
  browser: true
  commonjs: true
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
    globalReturn: true
    impliedStrict: true
rules:
  comma-dangle: 0
  semi: 0
  arrow-parens: 0
  # jsx-a11y/href-no-hash: 0
  # react/jsx-uses-vars: warn
  react/jsx-filename-extension: 0
  # react/display-name: warn
  # no-unused-vars: error
  # no-console: error
  # no-unexpected-multiline: error
settings:
  react:
    pragma: React
    version: "16.9.0"
