---
plugins:
  - react
  - jsx-a11y
  - import
  - prettier
extends:
  - airbnb
  - plugin:react/recommended
  - prettier
  - plugin:prettier/recommended
ignorePatterns:
  - 'public/*'
env:
  browser: true
  commonjs: true
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
    globalReturn: true
    impliedStrict: true
rules:
  comma-dangle: 0
  semi: 0
  arrow-parens: 0
  jsx-a11y/href-no-hash: 0
  react/jsx-filename-extension: 0
  # Ratchet these down over time
  react/prop-types: 1
  no-unused-vars: 1
  react/destructuring-assignment: 1
  react/require-default-props: 1
  jsx-a11y/anchor-is-valid: 1
  import/no-named-as-default: 1
  react/prefer-stateless-function: 1
  react/forbid-prop-types: 1
  react/display-name: 1
  consistent-return: 1
settings:
  react:
    pragma: React
    version: '17.2.0'
