[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"


[[redirects]]
  from = "https://keen-montalcini-f453b2.netlify.com/*"
  to = "https://www.doneops.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/casestudies/*"
  to = "/case-studies/:splat"
  status = 301
  force = true
